trigger: none

pool: shahedali-pipeline

stages:
  - stage: terraformInstall
    displayName: Terraform Installation
    jobs:
      - job: TerraformSetup
        displayName: Install and Run Terraform Commands
        pool: shahedali-pipeline
        steps:
          - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@2
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)Todo_app_infra/dev/'
              backendServiceArm: 'shahedali-pipeline'
              backendAzureRmStorageAccountName: 'shahed490'
              backendAzureRmContainerName: 'shahed'
              backendAzureRmKey: 'shahed.terraform.tfstate'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)Todo_app_infra/dev/'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)Todo_app_infra/dev/'
              environmentServiceNameAzureRM: 'shahedali-pipeline'

  - stage: securityTools
    displayName: Security Tool Scanning
    jobs:
    - job: SecurityScan
      displayName: Run tfsec (local scan)
      pool: shahedali-pipeline
      steps:
        - powershell: |
            Write-Host "Running local tfsec scan from custom directory..."

            # Define tfsec path manually (update this to your actual location)
            $tfsecPath = "D:\software\security_tools\tfsec.exe"

            if (-not (Test-Path $tfsecPath)) {
                Write-Host "tfsec not found at path: $tfsecPath"
                exit 0
            }

            # Run tfsec using full path
            & $tfsecPath "$(System.DefaultWorkingDirectory)\Todo_app_infra\dev\" --no-update-check --soft-fail

          displayName: Run tfsec from local path


  - stage: deployment
    displayName: Deploy
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    jobs: 
      - job: ManualValidation
        displayName: Manual Validation
        pool: server
        steps:
          - task: ManualValidation@1
            inputs:
              notifyUsers: 'shahedali2001@gmail.com'
              approvers: 'shahedali2001@gmail.com'
              instructions: 'planas to deploy to deployment. Please approve.'

      - job: TerraformApply
        displayName: Terraform Apply
        dependsOn: ManualValidation
        pool: shahedali-pipeline
        steps: 
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)Todo_app_infra/dev/'
              backendServiceArm: 'shahedali-pipeline'
              backendAzureRmStorageAccountName: 'shahed490'
              backendAzureRmContainerName: 'shahed'
              backendAzureRmKey: 'shahed.terraform.tfstate'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)Todo_app_infra/dev/'
              environmentServiceNameAzureRM: 'shahedali-pipeline'

